### PR TITLE
CMSP-314: Add specific surrogate key for post type archives

### PR DESCRIPTION
**Pull request by rwagner00**
(Original PR #222 ) Adds a surrogate key to post-type archive pages (eg, "portfolio) that's specific to that archive( eg portfolio-archive)

Also clears the post type archive when a post of that type is updated

### CODE REVIEW

**Comment by jspellman814** [comment]
Please make this PR against `develop`. See [CONTRIBUTING.md](https://github.com/pantheon-systems/pantheon-advanced-page-cache/blob/master/CONTRIBUTING.md#workflow) about workflow and release process.

**Review by jazzsequence — DISMISSED** [review]
lgtm, should we roll a new release for this?

**Comment by scottbuscemi** [comment]
Please do make a release :) TY

**Comment by rwagner00** [comment]
@jazzsequence -- Switched to being against develop

**Review by jazzsequence — APPROVED** [review]

**Comment by carl-alberto** [comment]
Also added a doc PR https://github.com/pantheon-systems/pantheon-advanced-page-cache/pull/227 to reflect the changes

**Pull request merged**
